import type { Lang } from "@/lib/i18n-data";

export const brand = {
  name: "Guru Gasthaus",
  first: "Guru",
  second: "Gasthaus",
  email: "hello@gurugasthaus.com",
  domain: "gurugasthaus.com",
};

export const siteCopy = {
  EN: {
    common: {
      contactUs: "Contact Us",
      askQuestion: "Ask a Question",
      startBooking: "Start Booking",
      paymentQuestions: "Payment Questions",
      viewHostFamilies: "View Host Families",
      browseHostFamilies: "Browse Host Families",
      getNotified: "Get Notified",
      contactOurTeam: "Contact our team",
      howItWorks: "How It Works",
      planYourStay: "Plan Your Stay",
      bookNowFrom: "Book Now -- From CHF 2,700",
      requestStayFrom: "Request to Stay -- From CHF 2,700",
      requestStay: "Request to Stay",
      available: "Available",
      unavailable: "Unavailable",
      availableNow: "Available Now",
      lastUpdated: "Last updated: May 2026",
      recommended: "Recommended",
      standard: "Standard",
      premium: "Premium",
      from: "From",
      included: "Included",
      notIncluded: "Not included",
      withFlight: "With flight ticket",
      withoutFlight: "Without flight ticket",
      estimatedTotal: "Estimated total",
      package: "Package",
      flightTicket: "Flight ticket",
      toggleMenu: "Toggle menu",
    },
    media: {
      logoAlt: "Guru Gasthaus",
      navHome: "Guru Gasthaus home",
      heroRiver: "Boat on a Bangladeshi river at sunset",
      familyLiving: "Dining and living room inside a Bangladeshi host family home",
      hostEntrance: "Entrance of a Bangladeshi host family home",
      bedroomWindow: "Guest bedroom with window in a Bangladeshi host home",
      bedroomBlue: "Guest bedroom in a Bangladeshi host home",
      homeKitchen: "Kitchen inside a Bangladeshi host family home",
      sittingRoom: "Sitting room in a Bangladeshi host family home",
      waterLilies: "Person gathering water lilies in Bangladesh",
      riverside: "Sunset over a Bangladeshi riverside",
      cargoBoat: "Cargo boat on a Bangladeshi river",
      familyRoom: "Family sitting room inside a host home",
      packageHero: "A welcoming Bangladeshi family home prepared for shared daily life",
      hostPreview: "host family preview",
    },
    home: {
      tags: ["Verified Host Families", "All-Inclusive", "Cultural Immersion", "2-Week Stay", "Airport Transfer"],
      ctaContact: "Contact Us",
      heroStats: { days: "Days Immersion", price: "Starting From" },
      host: {
        eyebrow: "Featured Host Family",
        headlineA: "Meet your",
        headlineB: "future host family",
        name: "Featured Host Family",
        location: "Bangladesh -- exact family details shared after booking review",
        quote: "A warm, carefully selected Bangladeshi household welcomes guests into everyday family life, shared meals, local routines, and cultural exchange.",
        facts: [
          ["Languages spoken", "Bangla, English, Hindi"],
          ["Household size", "5-6 people"],
          ["Amenities", "Private room, A/C, WiFi, rooftop terrace"],
        ],
      },
      gallery: {
        eyebrow: "In Their World",
        headline: "Glimpses of",
        emphasis: "everyday life",
      },
      faq: {
        headlineA: "Common",
        headlineB: "questions",
        intro: "Can't find what you're looking for? Our team responds to all enquiries within 24 hours.",
        items: [
          ["What is included in the price?", "All packages include airport pickup and dropoff, all three daily meals cooked by the host family, local transportation, cultural activities, and guided sightseeing. The Premium package adds cooking classes, music and crafts workshops, and additional tours. International flights can be added as an optional extra."],
          ["How do I book?", "Choose your package and dates, then email the prepared booking request. You'll receive payment details after the request is reviewed. Your booking is confirmed once payment is received."],
          ["Can I choose my host family?", "Yes -- you browse all available host family profiles before booking. Each profile includes family photos, a bio, location, amenities, languages spoken, and an availability calendar. You select the family that feels right for you."],
          ["What if I have dietary restrictions?", "Note your dietary requirements during booking and we'll communicate them to your host family before arrival. Bangladeshi cooking is naturally rich in vegetables and fish; most restrictions can be accommodated with advance notice."],
          ["Is it safe to travel to Bangladesh?", "Bangladesh is a welcoming and hospitable country. All our host families are carefully vetted and located in safe residential areas. You'll have local support from your family throughout your stay, and we remain reachable for the full duration of your visit."],
          ["How do I get from the airport?", "Airport pickup is included in every package. Your host family or a designated representative will be waiting at Hazrat Shahjalal International Airport when you land. Share your flight details at booking and we'll handle the rest."],
          ["What should I pack?", "Light, modest clothing is recommended. Bangladesh is warm and humid, and some cultural sites require covered shoulders and knees. We'll send a detailed pre-departure guide with a full packing list and local customs information before you arrive."],
        ],
      },
      packages: {
        withoutFlight: "Without Flight",
        withFlight: "With Flight Ticket",
        sections: [
          {
            section: "Included in all packages",
            items: [
              "14-night stay with host family",
              "All meals -- breakfast, lunch & dinner",
              "Airport pickup & dropoff",
              "Local transportation throughout stay",
              "Cultural activities & local sightseeing",
            ],
          },
          {
            section: "Premium only",
            items: [
              "Bengali cooking classes",
              "Traditional music sessions & crafts workshops",
              "Additional guided local tours & excursions",
              "More elaborate & varied meal offerings",
            ],
          },
        ],
        note: "All prices are listed in CHF. Payment details are sent by invoice after booking. Personal market purchases, souvenirs, and international flights (unless selected) are not included.",
      },
      payment: {
        eyebrow: "Payment",
        headlineA: "Simple",
        headlineB: "payment process",
        intro: "After booking, you'll receive a payment invoice by email with the details needed to complete your transfer. Your booking is reviewed and confirmed once payment is received.",
        flow: "Payment Flow",
        details: "Payment Details",
        detailsText: "The booking flow keeps payment clear and separate from package selection, so guests understand what happens after submitting a booking.",
        expect: "What to Expect",
        steps: [
          ["1.", "Submit Booking", "Choose your dates, package, and complete the booking form."],
          ["2.", "Receive Payment Details", "A payment invoice is sent to your email after the request is reviewed."],
          ["3.", "Complete Payment", "Use the invoice details to complete the payment from your bank."],
          ["4.", "Confirmed", "We verify payment and send your welcome pack & pre-arrival guide."],
        ],
        notes: [
          ["Invoice by email", "Payment details sent after booking"],
          ["Bank transfer", "Complete payment through your own bank"],
          ["Manual confirmation", "Booking is confirmed after payment review"],
          ["No card checkout", "No online card gateway is required"],
        ],
        cancellation: {
          eyebrow: "Cancellation Policy",
          headline: "Fair & transparent",
          emphasis: "refund policy",
          firstWindow: "Within 7 days of booking",
          firstText: "Cancel within the first week and receive 80% of your payment back -- no questions asked.",
          secondWindow: "After 7 days",
          secondText: "Life happens. If you need to cancel after the first week, a 50% refund is processed promptly.",
          rescheduleTitle: "Need to reschedule?",
          rescheduleText: "We're happy to help you find new dates with the same host family where possible.",
        },
      },
      testimonials: {
        eyebrow: "Guest Stories",
        headlineA: "What guests came",
        headlineB: "home saying",
        items: [
          ["Sophie Baumann", "Zurich, Switzerland", "I've travelled to 40 countries and this was genuinely unlike anything else. My host family treated me like a daughter. I came for two weeks and cried when I had to leave."],
          ["Markus Keller", "Munich, Germany", "The food, the warmth, the conversations -- I had no idea Bangladesh was so beautiful. It was the best trip of my life, without exaggeration."],
          ["Thomas Conti", "Milan, Italy", "The cooking classes, the music session on the third evening, the market visit with the grandmother -- moments I will carry my whole life."],
        ],
      },
      includes: {
        eyebrow: "What's Included",
        headlineA: "Everything you need,",
        headlineB: "taken care of",
        left: [
          ["i.", "Airport Transfer", "Your host family meets you on arrival and sees you off on departure day."],
          ["ii.", "All Meals", "Three meals a day -- freshwater fish curries, rooftop breakfasts, festive dinners -- cooked by the family."],
          ["iii.", "Local Transportation", "Rickshaws, CNGs, ferries -- you'll get around the Bangladeshi way, fully arranged by your host family."],
        ],
        right: [
          ["iv.", "Cultural Activities", "Visits to mosques, temples, markets, riverbanks, and local festivals -- guided by people who call this home."],
          ["v.", "Local Sightseeing Tours", "Guided tours across the city and surrounding areas -- history, nature, and daily life in one stay."],
          ["vi.", "Host Family Home", "A private room in a real family home -- not a guesthouse, not a hotel."],
        ],
        notIncluded: ["Personal market purchases", "Souvenirs & gifts", "Personal expenses", "International flights (unless selected)"],
      },
    },
    pages: {
      about: {
        eyebrow: "About Us",
        headline: "We Believe Travel Should",
        emphasis: "Feel Like Home",
        storyTitle: "Our Story",
        story: [
          "Guru Gasthaus was born from a simple belief: the most meaningful travel experiences don't happen in hotels. They happen around kitchen tables, in family courtyards, and on evening walks through local neighbourhoods.",
          "We created this platform to bridge the gap between curious travellers and the rich, generous culture of Bangladesh. We want the world to see what we see: a country of extraordinary warmth, stunning landscapes, and people who open their homes and hearts with remarkable ease.",
        ],
        workTitle: "What We Do",
        work: [
          "We carefully match international guests with a host family in Bangladesh for a fully immersive 2-week stay. Everything is included: meals, local transport, cultural activities, and airport transfers, so you can focus entirely on the experience.",
          "Whether you join a cooking class, visit a local bazaar, or simply sit and talk over chai, every moment is genuine. Nothing is staged. Everything is real.",
        ],
        guides: "What",
        guidesEmphasis: "guides us",
        values: [
          ["Authenticity", "We don't create performances for tourists. We invite you into real homes and real lives."],
          ["Respect", "We work closely with our host families to ensure the experience is enriching for both guests and hosts."],
          ["Connection", "We believe cultural exchange makes the world better, one stay at a time."],
        ],
        ctaTitle: "Ready to see Bangladesh",
        ctaEmphasis: "differently?",
        ctaText: "Browse our host families and start planning your immersive two-week stay.",
      },
      booking: {
        eyebrow: "Booking",
        headline: "Book your Bangladeshi",
        emphasis: "homestay experience",
        intro: "Submit your booking request and receive confirmation with a Swiss QR payment invoice by email. Payment is completed after submission, not on this page.",
        afterTitle: "Payment after booking",
        afterText: "After the request is reviewed, a Swiss QR-invoice PDF is sent to your email. Scan it with your Swiss banking app to fill in the transfer details and complete payment.",
        opened: "Email Draft Opened",
        openedTitle: "Send the prepared email to complete your request.",
        openedText: "Your email app should contain the booking details. Send it to {email}. We will review it and reply with the payment invoice. Your booking is confirmed only after payment is received.",
        selectedPackage: "Selected package",
        choosePackage: "Choose your package",
        standardDesc: "Host family stay, meals, local transport, and basic cultural activities.",
        premiumDesc: "Standard inclusions plus extended cooking, music, crafts, and local tours.",
        includeFlight: "Include international flight ticket",
        flightExtra: "Adds CHF 1,500 to the selected package.",
        guestDetails: "Guest details",
        travelPrefs: "Travel preferences",
        notesLabel: "Dietary needs, accessibility needs, or questions",
        notesPlaceholder: "Tell us anything important before we review your booking.",
        summary: "Booking summary",
        summaryNote: "Payment is not collected on this page. A Swiss QR payment invoice is sent by email after the booking request is reviewed.",
        submit: "Email Booking Request",
        subject: "Booking request: {package} package",
        fields: {
          firstName: "First name",
          lastName: "Last name",
          email: "Email",
          phone: "Phone",
          country: "Country",
          countryResidence: "Country of residence",
          guests: "Number of guests",
          package: "Package",
          flight: "Flight ticket",
          total: "Estimated total",
          arrival: "Preferred arrival",
          departure: "Preferred departure",
          notes: "Notes",
        },
      },
      contact: {
        eyebrow: "Contact",
        headline: "Get in touch with",
        emphasis: "our team",
        intro: "Have questions about your stay, need help booking, or want to learn more about the experience? We'd love to hear from you.",
        formTitle: "Send us a message",
        openedTitle: "Email draft opened",
        openedText: "Send the prepared message to {email}. We'll reply within 24 hours.",
        formAria: "Contact form",
        placeholders: {
          firstName: "Your first name",
          lastName: "Your last name",
          email: "your@email.com",
          message: "Tell us how we can help...",
        },
        subjects: ["General Inquiry", "Booking Question", "Host Family Information", "Payment & Invoice", "Cancellation", "Other"],
        submit: "Email Message",
        infoTitle: "Contact information",
        proverb: "A table set for guests is a prayer answered in Bangladesh.",
        proverbSource: "Bengali Proverb",
        responseTime: "Response time",
        responseValue: "Within 24 hours",
        defaultSubject: "Website enquiry",
        fields: {
          firstName: "First name",
          lastName: "Last name",
          email: "Email",
          subject: "Subject",
          message: "Message",
        },
      },
      faq: {
        eyebrow: "FAQ",
        headline: "Frequently asked",
        emphasis: "questions",
        intro: "Everything you need to know about booking, your stay, payment, and more.",
        stillTitle: "Still have questions?",
        stillText: "We're happy to help. Reach out and we'll get back to you within 24 hours.",
        categories: [
          ["Booking & Payment", [
            ["How do I book?", "Choose your package and dates, then email the prepared booking request. You'll receive payment details after the request is reviewed. Your booking is confirmed once payment is received."],
            ["How does payment work?", "After booking, you'll receive a payment invoice by email with the details needed to complete your transfer. Your booking is reviewed and confirmed once payment is received."],
            ["Can I cancel my booking?", "80% refund if cancelled within 7 days of booking. 50% refund if cancelled after 7 days. The 7-day window is measured from the date of booking confirmation."],
            ["What's included in the price?", "All packages include a two-week stay with host family, three meals per day, local transportation, airport pickup and dropoff, cultural activities, and local tours. The Premium package adds cooking classes, music sessions, crafts workshops, and additional tours."],
          ]],
          ["Your Stay", [
            ["Can I choose my host family?", "Yes -- you browse all available host family profiles before booking. Each profile includes family photos, a bio, location, amenities, languages spoken, and an availability calendar."],
            ["What if I have dietary restrictions?", "Note your dietary requirements during booking and we'll communicate them to your host family before arrival. Bangladeshi cooking is naturally rich in vegetables and fish; most restrictions can be accommodated with advance notice."],
            ["How long is the stay?", "All packages are for a two-week (14-night) stay. This duration allows for genuine cultural immersion."],
            ["What should I pack?", "Light, modest clothing is recommended. Bangladesh is warm and humid, and some cultural sites require covered shoulders and knees. We'll send a detailed pre-departure guide with a full packing list."],
          ]],
          ["Safety & Support", [
            ["Is it safe?", "All our host families are carefully vetted for safety, comfort, and hospitality. Bangladesh is known for its warm hospitality. Your host family ensures you feel safe and supported, and we remain reachable throughout your stay."],
            ["How do I get from the airport?", "Airport pickup is included in every package. Your host family or designated representative will be waiting at Hazrat Shahjalal International Airport when you land."],
          ]],
        ],
      },
      how: {
        steps: [
          ["1", "Choose your package", "Pick Standard or Premium, with or without a flight ticket included."],
          ["2", "Email your booking request", "Fill out the booking form, send the prepared email, and receive payment details after review."],
          ["3", "Arrive & immerse yourself", "Your host family will be at the airport to welcome you. From there, your Bengali adventure begins."],
        ],
        ctaTitle: "Ready to start your Bangladeshi",
        ctaEmphasis: "journey?",
        ctaText: "Browse our host families and find the perfect match for your two-week cultural immersion.",
      },
      hosts: {
        eyebrow: "Host Families",
        headline: "Meet the families who will",
        emphasis: "welcome you home",
        intro: "Each of our host families has been personally vetted for comfort, safety, and genuine Bangladeshi hospitality. Choose the family that feels right for you.",
        cards: [
          ["featured-host-family", "Featured Host Family", "Bangladesh", "A warm, carefully selected household prepared to welcome guests into everyday family life, home-cooked meals, and local cultural routines.", "Bangla, English, Hindi"],
          ["future-host-family", "Future Host Family", "Bangladesh", "Additional host homes will be added as the platform expands. Family identity and exact location remain private until the booking process.", "Bangla, English"],
          ["seasonal-host-family", "Seasonal Host Family", "Bangladesh", "A seasonal host profile reserved for future availability. Details will be shown only when the home is approved and ready for guests.", "Bangla, English"],
        ],
        moreTitle: "More families joining soon",
        moreText: "We're expanding to more cities across Bangladesh. Sign up to be notified when new host families become available.",
      },
      hostProfile: {
        back: "Back to Host Families",
        name: "Featured Host Family",
        location: "Bangladesh -- exact family details shared after booking review",
        quote: "A warm, carefully selected Bangladeshi household welcomes guests into everyday family life, shared meals, local routines, and cultural exchange.",
        facts: [
          ["Languages spoken", "Bangla, English, Hindi"],
          ["Household size", "5-6 people"],
          ["Amenities", "Private room, A/C, WiFi, rooftop terrace"],
          ["Availability", ""],
        ],
        months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        overview: "Household Overview",
        members: [
          ["Host parent", "Coordinates household routines, meals, and guest welcome."],
          ["Host parent", "Shares cooking traditions, daily life, and cultural context."],
          ["Younger household members", "May join conversations, meals, and everyday family moments."],
          ["Extended family", "Visits and shared meals may be part of the natural household rhythm."],
        ],
        ctaTitle: "Ready to meet your host family?",
        ctaText: "Book your two-week immersive stay and experience Bangladesh like a local.",
      },
      packages: {
        metadataTitle: "Student Experience -- Guru Gasthaus",
        metadataDescription: "Discover the tailored student homestay experience offered by Guru Gasthaus in Bangladesh.",
        eyebrow: "Student Experience",
        headline: "Learn Bangladesh by",
        emphasis: "living it.",
        intro: "A tailored homestay for students who want more than a tour. Live with a host family, take part in everyday life, and discover the country through people, food, and shared experience.",
        experienceEyebrow: "What You Will Experience",
        experienceHeadline: "A stay shaped around",
        experienceEmphasis: "curiosity and connection",
        experiences: [
          ["01", "Live with a local family", "Stay in a real Bangladeshi home, share meals, and become part of the household's daily rhythm."],
          ["02", "Learn through daily life", "Explore local markets, cook traditional food, practise language, and learn through genuine conversation."],
          ["03", "Experience the culture", "Join cultural activities, neighbourhood visits, river journeys, workshops, and locally planned excursions."],
          ["04", "Travel with support", "Airport transfers, meals, local transport, and personal guidance are arranged around your stay."],
        ],
        requestEyebrow: "Tailored On Request",
        requestTitle: "Tell us what you want to learn and experience.",
        requestText: "Every student stay is planned around dates, interests, group size, and travel needs. Contact our team for availability and a tailored proposal.",
      },
      legal: {
        privacyTitle: "Privacy Policy",
        termsTitle: "Terms & Conditions",
        privacy: [
          ["1. Information We Collect", "We collect personal information that you provide when using our platform, including: name, email address, phone number, country of residence, booking preferences, and payment information. We also collect usage data such as pages visited and time spent on our website."],
          ["2. How We Use Your Information", "Your information is used to process bookings, communicate booking confirmations and invoices, provide customer support, improve our platform, and comply with legal obligations. We do not sell your personal data to third parties."],
          ["3. Payment Information", "Payment is processed by invoice and bank transfer. We do not collect or store credit card information. Invoice and payment records are retained for accounting and legal purposes."],
          ["4. Data Sharing", "We share necessary booking information with your assigned host family, including your name, nationality, dietary preferences, and arrival details. We may share anonymized, aggregated data for analytics purposes."],
          ["5. Data Security", "We implement appropriate technical and organizational measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction. This includes encrypted data transmission (SSL/TLS) and secure storage practices."],
          ["6. Cookies", "Our website uses cookies to improve your browsing experience and analyze website traffic. You can manage cookie preferences through your browser settings. Essential cookies are required for the website to function properly."],
          ["7. Your Rights", "You have the right to access your personal data, request correction or deletion, and object to processing. You may also request data portability. To exercise these rights, please contact us at hello@gurugasthaus.com."],
          ["8. Data Retention", "We retain your personal data only for as long as necessary to fulfill the purposes outlined in this policy, typically no longer than 3 years after your last interaction with our service, unless a longer retention period is required by law."],
          ["9. Changes to This Policy", "We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated revision date."],
          ["10. Contact", "For privacy-related inquiries, contact us at hello@gurugasthaus.com."],
        ],
        terms: [
          ["1. General", "These Terms and Conditions govern the use of the Guru Gasthaus platform and the booking of homestay experiences in Bangladesh. By using our website and booking a stay, you agree to these terms in full."],
          ["2. Booking and Payment", "Bookings are confirmed after submission and payment. Payment is processed by invoice and bank transfer. No credit card is required at the time of booking. After submitting your booking, you will receive a confirmation email with payment details. All prices are listed in CHF."],
          ["3. Cancellation Policy", "Cancellations made within 7 days of the booking date are eligible for an 80% refund. Cancellations made after 7 days of the booking date are eligible for a 50% refund. The 7-day window is measured from the date of booking confirmation, not the travel start date."],
          ["4. What's Included", "All packages include a two-week stay with a host family, three meals per day, local transportation, airport pickup and dropoff, cultural activities, and local tours. The Premium package additionally includes cooking classes, music sessions, crafts workshops, and additional local tours."],
          ["5. What's Not Included", "Personal market purchases, souvenirs, personal expenses, and international flights are not included unless the guest selects a package with a flight ticket."],
          ["6. Host Family Placement", "Guests may choose their preferred host family based on availability. Guru Gasthaus reserves the right to reassign guests to another host family if the originally selected host becomes unavailable. In such cases, guests will be notified in advance and given the option to accept the alternative or receive a full refund."],
          ["7. Liability", "Guru Gasthaus acts as an intermediary between guests and host families. While we carefully vet all host families, we are not liable for personal injury, loss of property, or other incidents that may occur during the stay. Guests are advised to obtain appropriate travel insurance."],
          ["8. Privacy", "We respect your privacy. Please review our Privacy Policy for details on how we collect, use, and protect your personal information."],
          ["9. Changes to Terms", "Guru Gasthaus reserves the right to update these Terms and Conditions at any time. Changes will be posted on this page with an updated revision date."],
          ["10. Contact", "For questions about these terms, please contact us at hello@gurugasthaus.com."],
        ],
      },
    },
  },
} as const;

type Widen<T> = T extends string
  ? string
  : T extends readonly (infer U)[]
    ? readonly Widen<U>[]
    : T extends object
      ? { [K in keyof T]: Widen<T[K]> }
      : T;

type EnglishCopy = Widen<typeof siteCopy.EN>;

const phraseTranslations: Record<Exclude<Lang, "EN">, Record<string, string>> = {
  DE: {
    "Book Now -- From CHF 2,700": "Jetzt buchen -- ab CHF 2,700",
    "Request to Stay -- From CHF 2,700": "Aufenthalt anfragen -- ab CHF 2,700",
    "Request to Stay": "Aufenthalt anfragen",
    "Payment": "Zahlung",
    "Simple": "Einfacher",
    "payment process": "Zahlungsprozess",
    "After booking, you'll receive a payment invoice by email with the details needed to complete your transfer. Your booking is reviewed and confirmed once payment is received.": "Nach der Buchung erhaeltst du per E-Mail eine Zahlungsrechnung mit allen Details fuer die Ueberweisung. Deine Buchung wird geprueft und nach Zahlungseingang bestaetigt.",
    "Payment Flow": "Zahlungsablauf",
    "Payment Details": "Zahlungsdetails",
    "The booking flow keeps payment clear and separate from package selection, so guests understand what happens after submitting a booking.": "Der Buchungsablauf trennt Zahlung und Paketauswahl klar, damit Gaeste verstehen, was nach dem Absenden der Buchung passiert.",
    "What to Expect": "Was dich erwartet",
    "Submit Booking": "Buchung senden",
    "Choose your dates, package, and complete the booking form.": "Waehle Daten und Paket und fuelle das Buchungsformular aus.",
    "Receive Payment Details": "Zahlungsdetails erhalten",
    "A payment invoice is sent to your email after the request is reviewed.": "Nach Pruefung deiner Anfrage wird eine Zahlungsrechnung per E-Mail gesendet.",
    "Complete Payment": "Zahlung abschliessen",
    "Use the invoice details to complete the payment from your bank.": "Nutze die Rechnungsdetails, um die Zahlung ueber deine Bank abzuschliessen.",
    "Confirmed": "Bestaetigt",
    "We verify payment and send your welcome pack & pre-arrival guide.": "Wir pruefen die Zahlung und senden dir Willkommenspaket und Vorab-Guide.",
    "Invoice by email": "Rechnung per E-Mail",
    "Payment details sent after booking": "Zahlungsdetails nach der Buchung",
    "Bank transfer": "Bankueberweisung",
    "Complete payment through your own bank": "Zahlung ueber deine eigene Bank abschliessen",
    "Manual confirmation": "Manuelle Bestaetigung",
    "Booking is confirmed after payment review": "Die Buchung wird nach Zahlungspruefung bestaetigt",
    "No card checkout": "Keine Kartenzahlung",
    "No online card gateway is required": "Kein Online-Kartengateway erforderlich",
    "Cancellation Policy": "Stornierungsbedingungen",
    "Fair & transparent": "Fair und transparent",
    "refund policy": "Rueckerstattungsregelung",
    "Within 7 days of booking": "Innerhalb von 7 Tagen nach Buchung",
    "Cancel within the first week and receive 80% of your payment back -- no questions asked.": "Storniere innerhalb der ersten Woche und erhalte 80% deiner Zahlung zurueck -- ohne Rueckfragen.",
    "After 7 days": "Nach 7 Tagen",
    "Life happens. If you need to cancel after the first week, a 50% refund is processed promptly.": "Falls du nach der ersten Woche stornieren musst, bearbeiten wir zeitnah eine Rueckerstattung von 50%.",
    "Need to reschedule?": "Musst du umbuchen?",
    "We're happy to help you find new dates with the same host family where possible.": "Wir helfen dir gern, wenn moeglich neue Daten mit derselben Gastfamilie zu finden.",
    "Guest Stories": "Gaestegeschichten",
    "What guests came": "Was Gaeste nach Hause",
    "home saying": "mitgenommen haben",
    "I've travelled to 40 countries and this was genuinely unlike anything else. My host family treated me like a daughter. I came for two weeks and cried when I had to leave.": "Ich bin in 40 Laender gereist, und das war wirklich anders als alles andere. Meine Gastfamilie behandelte mich wie eine Tochter. Ich kam fuer zwei Wochen und weinte, als ich gehen musste.",
    "The food, the warmth, the conversations -- I had no idea Bangladesh was so beautiful. It was the best trip of my life, without exaggeration.": "Das Essen, die Herzlichkeit, die Gespraeche -- ich hatte keine Ahnung, dass Bangladesch so schoen ist. Es war ohne Uebertreibung die beste Reise meines Lebens.",
    "The cooking classes, the music session on the third evening, the market visit with the grandmother -- moments I will carry my whole life.": "Die Kochkurse, die Musiksession am dritten Abend, der Marktbesuch mit der Grossmutter -- Momente, die ich mein Leben lang mitnehme.",
    "What's Included": "Was enthalten ist",
    "Everything you need,": "Alles, was du brauchst,",
    "taken care of": "ist organisiert",
    "Airport Transfer": "Flughafentransfer",
    "Your host family meets you on arrival and sees you off on departure day.": "Deine Gastfamilie holt dich bei der Ankunft ab und verabschiedet dich am Abreisetag.",
    "All Meals": "Alle Mahlzeiten",
    "Three meals a day -- freshwater fish curries, rooftop breakfasts, festive dinners -- cooked by the family.": "Drei Mahlzeiten pro Tag -- Fischcurrys, Dachterrassen-Fruehstueck, festliche Abendessen -- von der Familie gekocht.",
    "Local Transportation": "Lokaler Transport",
    "Rickshaws, CNGs, ferries -- you'll get around the Bangladeshi way, fully arranged by your host family.": "Rikschas, CNGs, Faehren -- du bewegst dich auf bangladeschische Art, organisiert von deiner Gastfamilie.",
    "Cultural Activities": "Kulturelle Aktivitaeten",
    "Visits to mosques, temples, markets, riverbanks, and local festivals -- guided by people who call this home.": "Besuche von Moscheen, Tempeln, Maerkten, Flussufern und lokalen Festen -- begleitet von Menschen, die hier zuhause sind.",
    "Local Sightseeing Tours": "Lokale Besichtigungstouren",
    "Guided tours across the city and surrounding areas -- history, nature, and daily life in one stay.": "Gefuehrte Touren durch Stadt und Umgebung -- Geschichte, Natur und Alltag in einem Aufenthalt.",
    "Host Family Home": "Zuhause der Gastfamilie",
    "A private room in a real family home -- not a guesthouse, not a hotel.": "Ein Privatzimmer in einem echten Familienzuhause -- kein Guesthouse, kein Hotel.",
    "Personal market purchases": "Persoenliche Einkaeufe auf Maerkten",
    "Souvenirs & gifts": "Souvenirs und Geschenke",
    "Personal expenses": "Persoenliche Ausgaben",
    "International flights (unless selected)": "Internationale Fluege (falls nicht ausgewaehlt)",
    "Booking": "Buchung",
    "Book your Bangladeshi": "Buche dein bangladeschisches",
    "homestay experience": "Homestay-Erlebnis",
    "Submit your booking request and receive confirmation with a Swiss QR payment invoice by email. Payment is completed after submission, not on this page.": "Sende deine Buchungsanfrage und erhalte die Bestaetigung mit Schweizer QR-Rechnung per E-Mail. Die Zahlung erfolgt nach dem Absenden, nicht auf dieser Seite.",
    "Payment after booking": "Zahlung nach der Buchung",
    "After the request is reviewed, a Swiss QR-invoice PDF is sent to your email. Scan it with your Swiss banking app to fill in the transfer details and complete payment.": "Nach Pruefung der Anfrage wird dir eine Schweizer QR-Rechnung als PDF per E-Mail gesendet. Scanne sie mit deiner Banking-App, um die Ueberweisung auszufuellen.",
    "Email Draft Opened": "E-Mail-Entwurf geoeffnet",
    "Send the prepared email to complete your request.": "Sende die vorbereitete E-Mail, um deine Anfrage abzuschliessen.",
    "Your email app should contain the booking details. Send it to {email}. We will review it and reply with the payment invoice. Your booking is confirmed only after payment is received.": "Deine E-Mail-App sollte die Buchungsdetails enthalten. Sende sie an {email}. Wir pruefen sie und antworten mit der Zahlungsrechnung. Deine Buchung ist erst nach Zahlungseingang bestaetigt.",
    "Selected package": "Ausgewaehltes Paket",
    "Choose your package": "Paket waehlen",
    "Host family stay, meals, local transport, and basic cultural activities.": "Aufenthalt bei einer Gastfamilie, Mahlzeiten, lokaler Transport und grundlegende kulturelle Aktivitaeten.",
    "Standard inclusions plus extended cooking, music, crafts, and local tours.": "Standard-Leistungen plus erweiterte Kochkurse, Musik, Handwerk und lokale Touren.",
    "Include international flight ticket": "Internationales Flugticket einschliessen",
    "Adds CHF 1,500 to the selected package.": "Fuegt dem ausgewaehlten Paket CHF 1,500 hinzu.",
    "Guest details": "Gaestedetails",
    "Travel preferences": "Reisewuensche",
    "Dietary needs, accessibility needs, or questions": "Ernaehrungswuensche, Barrierefreiheit oder Fragen",
    "Tell us anything important before we review your booking.": "Teile uns alles Wichtige mit, bevor wir deine Buchung pruefen.",
    "Booking summary": "Buchungsuebersicht",
    "Payment is not collected on this page. A Swiss QR payment invoice is sent by email after the booking request is reviewed.": "Auf dieser Seite wird keine Zahlung eingezogen. Nach Pruefung der Buchungsanfrage wird eine Schweizer QR-Rechnung per E-Mail gesendet.",
    "Email Booking Request": "Buchungsanfrage mailen",
    "Booking request: {package} package": "Buchungsanfrage: Paket {package}",
    "First name": "Vorname",
    "Last name": "Nachname",
    "Email": "E-Mail",
    "Phone": "Telefon",
    "Country": "Land",
    "Country of residence": "Wohnsitzland",
    "Number of guests": "Anzahl Gaeste",
    "Package": "Paket",
    "Flight ticket": "Flugticket",
    "Estimated total": "Geschaetzte Summe",
    "Preferred arrival": "Gewuenschte Ankunft",
    "Preferred departure": "Gewuenschte Abreise",
    "Notes": "Notizen",
    "Contact": "Kontakt",
    "Get in touch with": "Nimm Kontakt auf mit",
    "our team": "unserem Team",
    "Have questions about your stay, need help booking, or want to learn more about the experience? We'd love to hear from you.": "Hast du Fragen zum Aufenthalt, brauchst Hilfe bei der Buchung oder moechtest mehr erfahren? Wir freuen uns auf deine Nachricht.",
    "Send us a message": "Sende uns eine Nachricht",
    "Email draft opened": "E-Mail-Entwurf geoeffnet",
    "Send the prepared message to {email}. We'll reply within 24 hours.": "Sende die vorbereitete Nachricht an {email}. Wir antworten innerhalb von 24 Stunden.",
    "Contact form": "Kontaktformular",
    "Your first name": "Dein Vorname",
    "Your last name": "Dein Nachname",
    "Tell us how we can help...": "Sag uns, wie wir helfen koennen...",
    "General Inquiry": "Allgemeine Anfrage",
    "Booking Question": "Frage zur Buchung",
    "Host Family Information": "Informationen zur Gastfamilie",
    "Payment & Invoice": "Zahlung und Rechnung",
    "Cancellation": "Stornierung",
    "Other": "Sonstiges",
    "Email Message": "Nachricht mailen",
    "Contact information": "Kontaktinformationen",
    "A table set for guests is a prayer answered in Bangladesh.": "Ein gedeckter Tisch fuer Gaeste ist in Bangladesch ein erhoertes Gebet.",
    "Bengali Proverb": "Bengalisches Sprichwort",
    "Response time": "Antwortzeit",
    "Within 24 hours": "Innerhalb von 24 Stunden",
    "Website enquiry": "Website-Anfrage",
    "Subject": "Betreff",
    "Message": "Nachricht",
    "Frequently asked": "Haeufig gestellte",
    "questions": "Fragen",
    "Everything you need to know about booking, your stay, payment, and more.": "Alles, was du ueber Buchung, Aufenthalt, Zahlung und mehr wissen musst.",
    "Still have questions?": "Noch Fragen?",
    "We're happy to help. Reach out and we'll get back to you within 24 hours.": "Wir helfen gern. Melde dich und wir antworten innerhalb von 24 Stunden.",
    "Booking & Payment": "Buchung und Zahlung",
    "How does payment work?": "Wie funktioniert die Zahlung?",
    "Can I cancel my booking?": "Kann ich meine Buchung stornieren?",
    "Host Families": "Gastfamilien",
    "Meet the families who will": "Lerne die Familien kennen, die",
    "welcome you home": "dich zuhause willkommen heissen",
    "Back to Host Families": "Zurueck zu den Gastfamilien",
    "Availability": "Verfuegbarkeit",
    "Household Overview": "Haushaltsueberblick",
  },
  FR: {},
  IT: {},
};

phraseTranslations.FR = {
  ...phraseTranslations.DE,
  "Simple": "Processus",
  "payment process": "de paiement simple",
  "Payment": "Paiement",
  "Payment Details": "Details du paiement",
  "The booking flow keeps payment clear and separate from package selection, so guests understand what happens after submitting a booking.": "Le parcours de reservation garde le paiement clair et separe du choix du forfait, afin que les invites comprennent ce qui se passe apres l'envoi.",
  "Payment Flow": "Etapes de paiement",
  "What to Expect": "A quoi s'attendre",
  "Booking": "Reservation",
  "Book your Bangladeshi": "Reservez votre experience",
  "homestay experience": "chez l'habitant au Bangladesh",
  "Choose your package": "Choisissez votre forfait",
  "Guest details": "Details des invites",
  "Travel preferences": "Preferences de voyage",
  "Booking summary": "Resume de reservation",
  "Contact": "Contact",
  "Frequently asked": "Questions",
  "questions": "frequentes",
  "Host Families": "Familles d'accueil",
  "Back to Host Families": "Retour aux familles d'accueil",
  "Availability": "Disponibilite",
  "Household Overview": "Apercu du foyer",
  "Guest Stories": "Histoires d'invites",
  "What guests came": "Ce que les invites",
  "home saying": "ont raconte en rentrant",
  "I've travelled to 40 countries and this was genuinely unlike anything else. My host family treated me like a daughter. I came for two weeks and cried when I had to leave.": "J'ai voyage dans 40 pays et cette experience etait vraiment differente de tout le reste. Ma famille d'accueil m'a traitee comme une fille. Je suis venue deux semaines et j'ai pleure en partant.",
  "The food, the warmth, the conversations -- I had no idea Bangladesh was so beautiful. It was the best trip of my life, without exaggeration.": "La cuisine, la chaleur humaine, les conversations -- je ne savais pas que le Bangladesh etait si beau. C'etait le plus beau voyage de ma vie, sans exageration.",
  "The cooking classes, the music session on the third evening, the market visit with the grandmother -- moments I will carry my whole life.": "Les cours de cuisine, la session de musique du troisieme soir, la visite du marche avec la grand-mere -- des moments que je garderai toute ma vie.",
};

phraseTranslations.IT = {
  ...phraseTranslations.DE,
  "Simple": "Processo",
  "payment process": "di pagamento semplice",
  "Payment": "Pagamento",
  "Payment Details": "Dettagli pagamento",
  "The booking flow keeps payment clear and separate from package selection, so guests understand what happens after submitting a booking.": "Il flusso di prenotazione mantiene il pagamento chiaro e separato dalla scelta del pacchetto, cosi gli ospiti capiscono cosa succede dopo l'invio.",
  "Payment Flow": "Flusso pagamento",
  "What to Expect": "Cosa aspettarsi",
  "Booking": "Prenotazione",
  "Book your Bangladeshi": "Prenota la tua esperienza",
  "homestay experience": "in famiglia in Bangladesh",
  "Choose your package": "Scegli il pacchetto",
  "Guest details": "Dettagli ospiti",
  "Travel preferences": "Preferenze di viaggio",
  "Booking summary": "Riepilogo prenotazione",
  "Contact": "Contatti",
  "Frequently asked": "Domande",
  "questions": "frequenti",
  "Host Families": "Famiglie ospitanti",
  "Back to Host Families": "Torna alle famiglie ospitanti",
  "Availability": "Disponibilita",
  "Household Overview": "Panoramica della casa",
  "Guest Stories": "Storie degli ospiti",
  "What guests came": "Cosa gli ospiti",
  "home saying": "raccontano al ritorno",
  "I've travelled to 40 countries and this was genuinely unlike anything else. My host family treated me like a daughter. I came for two weeks and cried when I had to leave.": "Ho viaggiato in 40 paesi e questa esperienza era davvero diversa da qualsiasi altra. La mia famiglia ospitante mi ha trattata come una figlia. Sono venuta per due settimane e ho pianto quando sono dovuta partire.",
  "The food, the warmth, the conversations -- I had no idea Bangladesh was so beautiful. It was the best trip of my life, without exaggeration.": "Il cibo, il calore, le conversazioni -- non immaginavo che il Bangladesh fosse cosi bello. E stato il viaggio piu bello della mia vita, senza esagerare.",
  "The cooking classes, the music session on the third evening, the market visit with the grandmother -- moments I will carry my whole life.": "Le lezioni di cucina, la sessione musicale della terza sera, la visita al mercato con la nonna -- momenti che portero con me per tutta la vita.",
};

phraseTranslations.FR = {
  ...phraseTranslations.FR,
  "Book Now -- From CHF 2,700": "Reserver -- des CHF 2,700",
  "Request to Stay -- From CHF 2,700": "Demander le sejour -- des CHF 2,700",
  "Request to Stay": "Demander le sejour",
};

phraseTranslations.IT = {
  ...phraseTranslations.IT,
  "Book Now -- From CHF 2,700": "Prenota ora -- da CHF 2,700",
  "Request to Stay -- From CHF 2,700": "Richiedi soggiorno -- da CHF 2,700",
  "Request to Stay": "Richiedi soggiorno",
};


function shouldKeepOriginal(value: string) {
  return (
    value.trim() === "" ||
    /^\d+[.,]?$/.test(value) ||
    /^CHF\b/.test(value) ||
    [brand.name, brand.email, brand.domain].includes(value) ||
    ["Standard", "Premium", "Bangladesh", "Bangla", "English", "Hindi", "WiFi", "A/C", "FAQ"].includes(value)
  );
}

function markUntranslated<T>(value: T, lang: Exclude<Lang, "EN">): T {
  if (typeof value === "string") {
    if (shouldKeepOriginal(value)) return value;
    return (phraseTranslations[lang][value] ?? value) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) => markUntranslated(item, lang)) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, markUntranslated(item, lang)]),
    ) as T;
  }

  return value;
}

const translatedCopy: Record<Exclude<Lang, "EN">, EnglishCopy> = {
  DE: {
    ...markUntranslated(siteCopy.EN, "DE"),
    common: {
      ...markUntranslated(siteCopy.EN.common, "DE"),
      contactUs: "Kontakt",
      askQuestion: "Frage stellen",
      startBooking: "Buchung starten",
      paymentQuestions: "Fragen zur Zahlung",
      viewHostFamilies: "Gastfamilien ansehen",
      browseHostFamilies: "Gastfamilien ansehen",
      getNotified: "Benachrichtigen lassen",
      contactOurTeam: "Team kontaktieren",
      howItWorks: "So funktioniert es",
      planYourStay: "Aufenthalt planen",
      available: "Verfuegbar",
      unavailable: "Nicht verfuegbar",
      availableNow: "Jetzt verfuegbar",
      lastUpdated: "Zuletzt aktualisiert: Mai 2026",
      recommended: "Empfohlen",
      from: "Ab",
      included: "Inbegriffen",
      notIncluded: "Nicht inbegriffen",
      withFlight: "Mit Flugticket",
      withoutFlight: "Ohne Flugticket",
      estimatedTotal: "Geschaetzte Summe",
      package: "Paket",
      flightTicket: "Flugticket",
      toggleMenu: "Menue umschalten",
    },
    home: {
      ...markUntranslated(siteCopy.EN.home, "DE"),
      tags: ["Gepruefte Gastfamilien", "Alles inklusive", "Kulturelle Immersion", "2 Wochen Aufenthalt", "Flughafentransfer"],
      ctaContact: "Kontakt",
      heroStats: { days: "Tage Immersion", price: "Ab" },
      host: {
        ...markUntranslated(siteCopy.EN.home.host, "DE"),
        eyebrow: "Ausgewaehlte Gastfamilie",
        headlineA: "Lerne deine",
        headlineB: "zukuenftige Gastfamilie kennen",
        name: "Ausgewaehlte Gastfamilie",
        location: "Bangladesch -- genaue Familiendetails nach Buchungspruefung",
        quote: "Ein warmherziger, sorgfaeltig ausgewaehlter bangladeschischer Haushalt heisst Gaeste im echten Familienalltag willkommen.",
        facts: [["Gesprochene Sprachen", "Bangla, Englisch, Hindi"], ["Haushaltsgroesse", "5-6 Personen"], ["Ausstattung", "Privatzimmer, A/C, WLAN, Dachterrasse"]],
      },
      gallery: { eyebrow: "In ihrer Welt", headline: "Einblicke in das", emphasis: "Alltagsleben" },
      faq: {
        ...markUntranslated(siteCopy.EN.home.faq, "DE"),
        headlineA: "Haeufige",
        headlineB: "Fragen",
        intro: "Du findest nicht, wonach du suchst? Unser Team antwortet innerhalb von 24 Stunden.",
        items: [
          ["Was ist im Preis inbegriffen?", "Alle Pakete enthalten Flughafentransfer, drei taegliche Mahlzeiten bei der Gastfamilie, lokalen Transport, kulturelle Aktivitaeten und gefuehrte Besichtigungen. Premium ergaenzt Kochkurse, Musik- und Handwerksworkshops sowie weitere Touren."],
          ["Wie buche ich?", "Waehle Paket und Daten und sende die vorbereitete Buchungsanfrage per E-Mail. Nach Pruefung erhaeltst du Zahlungsdetails. Die Buchung ist nach Zahlungseingang bestaetigt."],
          ["Kann ich meine Gastfamilie waehlen?", "Ja -- du siehst verfuegbare Gastfamilienprofile vor der Buchung und waehlst die Familie, die zu dir passt."],
          ["Was ist mit Ernaehrungseinschraenkungen?", "Nenne deine Anforderungen bei der Buchung. Wir geben sie vor deiner Ankunft an die Gastfamilie weiter."],
          ["Ist Reisen nach Bangladesch sicher?", "Bangladesch ist gastfreundlich. Unsere Gastfamilien werden sorgfaeltig geprueft und bieten dir waehrend des Aufenthalts lokale Unterstuetzung."],
          ["Wie komme ich vom Flughafen?", "Die Abholung am Flughafen ist in jedem Paket enthalten. Deine Gastfamilie oder eine Vertretung erwartet dich bei der Ankunft."],
          ["Was soll ich einpacken?", "Leichte, dezente Kleidung wird empfohlen. Vor der Abreise senden wir dir einen detaillierten Guide mit Packliste und lokalen Hinweisen."],
        ],
      },
      packages: {
        ...markUntranslated(siteCopy.EN.home.packages, "DE"),
        withoutFlight: "Ohne Flug",
        withFlight: "Mit Flugticket",
        sections: [
          { section: "In allen Paketen enthalten", items: ["14 Naechte bei einer Gastfamilie", "Alle Mahlzeiten -- Fruehstueck, Mittag- und Abendessen", "Flughafenabholung und Ruecktransfer", "Lokaler Transport waehrend des Aufenthalts", "Kulturelle Aktivitaeten und lokale Besichtigungen"] },
          { section: "Nur Premium", items: ["Bengalische Kochkurse", "Traditionelle Musik und Handwerksworkshops", "Zusaetzliche gefuehrte lokale Touren", "Umfangreichere und abwechslungsreichere Mahlzeiten"] },
        ],
        note: "Alle Preise sind in CHF. Zahlungsdetails werden nach der Buchung per Rechnung gesendet. Persoenliche Einkaeufe, Souvenirs und internationale Fluege sind nicht enthalten, ausser sie wurden ausgewaehlt.",
      },
    },
    pages: {
      ...markUntranslated(siteCopy.EN.pages, "DE"),
      about: {
        ...markUntranslated(siteCopy.EN.pages.about, "DE"),
        eyebrow: "Ueber uns",
        headline: "Wir glauben, Reisen sollte",
        emphasis: "sich wie Zuhause anfuehlen",
        storyTitle: "Unsere Geschichte",
        story: ["Guru Gasthaus entstand aus einer einfachen Ueberzeugung: Die bedeutsamsten Reiseerlebnisse passieren nicht in Hotels, sondern an Kuechentischen, in Familienhoefen und bei Spaziergaengen durch lokale Viertel.", "Wir verbinden neugierige Reisende mit der reichen und grosszuegigen Kultur Bangladeschs."],
        workTitle: "Was wir tun",
        work: ["Wir bringen internationale Gaeste fuer einen voll immersiven zweiwoechigen Aufenthalt mit einer Gastfamilie in Bangladesch zusammen.", "Ob Kochkurs, lokaler Basar oder Gespraech bei Chai: Jeder Moment ist echt."],
        guides: "Was uns",
        guidesEmphasis: "leitet",
        values: [["Authentizitaet", "Wir inszenieren nichts fuer Touristen. Wir laden dich in echte Zuhause und echte Leben ein."], ["Respekt", "Wir arbeiten eng mit unseren Gastfamilien zusammen, damit die Erfahrung fuer beide Seiten bereichernd ist."], ["Verbindung", "Kulturaustausch macht die Welt besser, ein Aufenthalt nach dem anderen."]],
        ctaTitle: "Bereit, Bangladesch",
        ctaEmphasis: "anders zu sehen?",
        ctaText: "Sieh dir unsere Gastfamilien an und plane deinen immersiven zweiwoechigen Aufenthalt.",
      },
      packages: {
        ...markUntranslated(siteCopy.EN.pages.packages, "DE"),
        eyebrow: "Studentenerlebnis",
        headline: "Lerne Bangladesch, indem du es",
        emphasis: "wirklich lebst.",
        intro: "Ein massgeschneiderter Homestay fuer Studierende, die mehr wollen als eine Tour. Lebe mit einer Gastfamilie, nimm am Alltag teil und entdecke das Land durch Menschen, Essen und gemeinsame Erfahrungen.",
        experienceEyebrow: "Was du erleben wirst",
        experienceHeadline: "Ein Aufenthalt voller",
        experienceEmphasis: "Neugier und Verbindung",
        experiences: [
          ["01", "Bei einer lokalen Familie leben", "Wohne in einem echten bangladeschischen Zuhause, teile Mahlzeiten und werde Teil des Alltagsrhythmus."],
          ["02", "Durch den Alltag lernen", "Erkunde lokale Maerkte, koche traditionelles Essen, uebe Sprache und lerne in echten Gespraechen."],
          ["03", "Kultur erleben", "Nimm an kulturellen Aktivitaeten, Nachbarschaftsbesuchen, Flussfahrten, Workshops und lokalen Ausfluegen teil."],
          ["04", "Mit Unterstuetzung reisen", "Flughafentransfers, Mahlzeiten, lokaler Transport und persoenliche Begleitung werden rund um deinen Aufenthalt organisiert."],
        ],
        requestEyebrow: "Auf Anfrage angepasst",
        requestTitle: "Sag uns, was du lernen und erleben moechtest.",
        requestText: "Jeder Studentenaufenthalt wird nach Daten, Interessen, Gruppengroesse und Reisebedarf geplant. Kontaktiere unser Team fuer Verfuegbarkeit und einen passenden Vorschlag.",
      },
    },
  },
  FR: {
    ...markUntranslated(siteCopy.EN, "FR"),
    common: {
      ...markUntranslated(siteCopy.EN.common, "FR"),
      contactUs: "Contact",
      askQuestion: "Poser une question",
      startBooking: "Commencer la reservation",
      paymentQuestions: "Questions de paiement",
      viewHostFamilies: "Voir les familles",
      browseHostFamilies: "Voir les familles",
      getNotified: "Etre informe",
      contactOurTeam: "Contacter l'equipe",
      howItWorks: "Comment ca marche",
      planYourStay: "Planifier le sejour",
      available: "Disponible",
      unavailable: "Indisponible",
      availableNow: "Disponible maintenant",
      lastUpdated: "Derniere mise a jour : mai 2026",
      recommended: "Recommande",
      from: "A partir de",
      included: "Inclus",
      notIncluded: "Non inclus",
      withFlight: "Avec billet d'avion",
      withoutFlight: "Sans billet d'avion",
      estimatedTotal: "Total estime",
      package: "Forfait",
      flightTicket: "Billet d'avion",
      toggleMenu: "Ouvrir ou fermer le menu",
    },
    home: {
      ...markUntranslated(siteCopy.EN.home, "FR"),
      tags: ["Familles verifiees", "Tout inclus", "Immersion culturelle", "Sejour de 2 semaines", "Transfert aeroport"],
      ctaContact: "Contact",
      heroStats: { days: "Jours d'immersion", price: "A partir de" },
      packages: {
        ...markUntranslated(siteCopy.EN.home.packages, "FR"),
        withoutFlight: "Sans vol",
        withFlight: "Avec billet d'avion",
        sections: [
          { section: "Inclus dans tous les forfaits", items: ["14 nuits chez une famille d'accueil", "Tous les repas -- petit-dejeuner, dejeuner et diner", "Accueil et retour a l'aeroport", "Transport local pendant le sejour", "Activites culturelles et visites locales"] },
          { section: "Premium seulement", items: ["Cours de cuisine bengalie", "Sessions de musique traditionnelle et ateliers d'artisanat", "Visites locales guidees supplementaires", "Repas plus varies et elabores"] },
        ],
        note: "Tous les prix sont indiques en CHF. Les details de paiement sont envoyes par facture apres la reservation. Les achats personnels, souvenirs et vols internationaux ne sont pas inclus sauf selection contraire.",
      },
    },
    pages: {
      ...markUntranslated(siteCopy.EN.pages, "FR"),
      about: {
        ...markUntranslated(siteCopy.EN.pages.about, "FR"),
        eyebrow: "A propos",
        headline: "Nous pensons que voyager doit",
        emphasis: "ressembler a un chez-soi",
        storyTitle: "Notre histoire",
        story: ["Guru Gasthaus est ne d'une conviction simple : les voyages les plus marquants ne se vivent pas a l'hotel, mais autour des tables de cuisine, dans les cours familiales et lors de promenades de quartier.", "Nous rapprochons les voyageurs curieux de la culture chaleureuse et genereuse du Bangladesh."],
        workTitle: "Ce que nous faisons",
        work: ["Nous mettons en relation des invites internationaux avec une famille d'accueil au Bangladesh pour un sejour immersif de deux semaines.", "Cours de cuisine, bazar local ou chai partage : chaque moment est authentique."],
        guides: "Ce qui",
        guidesEmphasis: "nous guide",
        values: [["Authenticite", "Nous ne creons pas de spectacles pour touristes. Nous vous invitons dans de vraies maisons et de vraies vies."], ["Respect", "Nous travaillons avec les familles afin que l'experience soit enrichissante pour tous."], ["Lien", "L'echange culturel rend le monde meilleur, un sejour a la fois."]],
        ctaTitle: "Pret a voir le Bangladesh",
        ctaEmphasis: "autrement ?",
        ctaText: "Decouvrez nos familles d'accueil et commencez a planifier votre sejour immersif de deux semaines.",
      },
      packages: {
        ...markUntranslated(siteCopy.EN.pages.packages, "FR"),
        eyebrow: "Experience etudiante",
        headline: "Apprenez le Bangladesh en le",
        emphasis: "vivant.",
        intro: "Un homestay sur mesure pour les etudiants qui veulent plus qu'une visite. Vivez avec une famille d'accueil, participez au quotidien et decouvrez le pays a travers les gens, la cuisine et l'experience partagee.",
        experienceEyebrow: "Ce que vous vivrez",
        experienceHeadline: "Un sejour construit autour de",
        experienceEmphasis: "la curiosite et du lien",
        experiences: [
          ["01", "Vivre avec une famille locale", "Sejournez dans une vraie maison bangladaise, partagez les repas et entrez dans le rythme quotidien du foyer."],
          ["02", "Apprendre par le quotidien", "Explorez les marches locaux, cuisinez des plats traditionnels, pratiquez la langue et apprenez par de vraies conversations."],
          ["03", "Vivre la culture", "Participez a des activites culturelles, visites de quartier, trajets fluviaux, ateliers et excursions locales."],
          ["04", "Voyager avec soutien", "Transferts aeroport, repas, transport local et accompagnement personnel sont organises autour de votre sejour."],
        ],
        requestEyebrow: "Adapte sur demande",
        requestTitle: "Dites-nous ce que vous voulez apprendre et vivre.",
        requestText: "Chaque sejour etudiant est planifie selon les dates, les centres d'interet, la taille du groupe et les besoins de voyage. Contactez notre equipe pour la disponibilite et une proposition sur mesure.",
      },
    },
  },
  IT: {
    ...markUntranslated(siteCopy.EN, "IT"),
    common: {
      ...markUntranslated(siteCopy.EN.common, "IT"),
      contactUs: "Contatti",
      askQuestion: "Fai una domanda",
      startBooking: "Inizia prenotazione",
      paymentQuestions: "Domande sul pagamento",
      viewHostFamilies: "Vedi famiglie ospitanti",
      browseHostFamilies: "Vedi famiglie ospitanti",
      getNotified: "Ricevi aggiornamenti",
      contactOurTeam: "Contatta il team",
      howItWorks: "Come funziona",
      planYourStay: "Pianifica il soggiorno",
      available: "Disponibile",
      unavailable: "Non disponibile",
      availableNow: "Disponibile ora",
      lastUpdated: "Ultimo aggiornamento: maggio 2026",
      recommended: "Consigliato",
      from: "Da",
      included: "Incluso",
      notIncluded: "Non incluso",
      withFlight: "Con biglietto aereo",
      withoutFlight: "Senza biglietto aereo",
      estimatedTotal: "Totale stimato",
      package: "Pacchetto",
      flightTicket: "Biglietto aereo",
      toggleMenu: "Apri o chiudi menu",
    },
    home: {
      ...markUntranslated(siteCopy.EN.home, "IT"),
      tags: ["Famiglie verificate", "Tutto incluso", "Immersione culturale", "Soggiorno di 2 settimane", "Transfer aeroporto"],
      ctaContact: "Contatti",
      heroStats: { days: "Giorni di immersione", price: "Da" },
      packages: {
        ...markUntranslated(siteCopy.EN.home.packages, "IT"),
        withoutFlight: "Senza volo",
        withFlight: "Con biglietto aereo",
        sections: [
          { section: "Incluso in tutti i pacchetti", items: ["14 notti con una famiglia ospitante", "Tutti i pasti -- colazione, pranzo e cena", "Pickup e ritorno in aeroporto", "Trasporto locale durante il soggiorno", "Attivita culturali e visite locali"] },
          { section: "Solo Premium", items: ["Corsi di cucina bengalese", "Sessioni di musica tradizionale e laboratori artigianali", "Tour locali guidati aggiuntivi", "Pasti piu ricchi e vari"] },
        ],
        note: "Tutti i prezzi sono in CHF. I dettagli di pagamento vengono inviati tramite fattura dopo la prenotazione. Acquisti personali, souvenir e voli internazionali non sono inclusi salvo selezione.",
      },
    },
    pages: {
      ...markUntranslated(siteCopy.EN.pages, "IT"),
      about: {
        ...markUntranslated(siteCopy.EN.pages.about, "IT"),
        eyebrow: "Chi siamo",
        headline: "Crediamo che viaggiare debba",
        emphasis: "sembrare casa",
        storyTitle: "La nostra storia",
        story: ["Guru Gasthaus nasce da una convinzione semplice: le esperienze di viaggio piu significative non accadono negli hotel, ma attorno ai tavoli di cucina, nei cortili familiari e nelle passeggiate nei quartieri.", "Colleghiamo viaggiatori curiosi con la cultura calda e generosa del Bangladesh."],
        workTitle: "Cosa facciamo",
        work: ["Abbiniamo ospiti internazionali a una famiglia ospitante in Bangladesh per un soggiorno immersivo di due settimane.", "Che sia una lezione di cucina, un bazar locale o una conversazione davanti al chai, ogni momento e autentico."],
        guides: "Cosa",
        guidesEmphasis: "ci guida",
        values: [["Autenticita", "Non creiamo spettacoli per turisti. Ti invitiamo in case vere e vite vere."], ["Rispetto", "Collaboriamo con le famiglie ospitanti affinche l'esperienza arricchisca tutti."], ["Connessione", "Lo scambio culturale rende il mondo migliore, un soggiorno alla volta."]],
        ctaTitle: "Pronto a vedere il Bangladesh",
        ctaEmphasis: "in modo diverso?",
        ctaText: "Scopri le famiglie ospitanti e inizia a pianificare il tuo soggiorno immersivo di due settimane.",
      },
      packages: {
        ...markUntranslated(siteCopy.EN.pages.packages, "IT"),
        eyebrow: "Esperienza studenti",
        headline: "Impara il Bangladesh",
        emphasis: "vivendolo.",
        intro: "Un homestay su misura per studenti che vogliono piu di un tour. Vivi con una famiglia ospitante, partecipa alla vita quotidiana e scopri il paese attraverso persone, cibo ed esperienze condivise.",
        experienceEyebrow: "Cosa vivrai",
        experienceHeadline: "Un soggiorno costruito su",
        experienceEmphasis: "curiosita e connessione",
        experiences: [
          ["01", "Vivere con una famiglia locale", "Soggiorna in una vera casa bangladese, condividi i pasti e diventa parte del ritmo quotidiano della famiglia."],
          ["02", "Imparare dalla vita quotidiana", "Esplora mercati locali, cucina piatti tradizionali, pratica la lingua e impara attraverso conversazioni autentiche."],
          ["03", "Vivere la cultura", "Partecipa ad attivita culturali, visite di quartiere, viaggi sul fiume, laboratori ed escursioni locali."],
          ["04", "Viaggiare con supporto", "Transfer aeroportuali, pasti, trasporto locale e guida personale sono organizzati intorno al tuo soggiorno."],
        ],
        requestEyebrow: "Su richiesta",
        requestTitle: "Dicci cosa vuoi imparare e vivere.",
        requestText: "Ogni soggiorno per studenti viene pianificato in base a date, interessi, dimensione del gruppo e necessita di viaggio. Contatta il nostro team per disponibilita e una proposta su misura.",
      },
    },
  },
};

export const copyByLang: Record<Lang, EnglishCopy> = {
  EN: siteCopy.EN,
  ...translatedCopy,
};

export type SiteCopy = EnglishCopy;
